/* eslint-disable */ //@ts-nocheck
/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 5.27.1
 * source: roomdata.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */ "use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
Object.defineProperty(exports, "com", {
    enumerable: true,
    get: function() {
        return com;
    }
});
const _class_private_field_loose_base = require("@swc/helpers/_/_class_private_field_loose_base");
const _class_private_field_loose_key = require("@swc/helpers/_/_class_private_field_loose_key");
const _interop_require_wildcard = require("@swc/helpers/_/_interop_require_wildcard");
const _googleprotobuf = /*#__PURE__*/ _interop_require_wildcard._(require("google-protobuf"));
var com;
(function(com) {
    (function(iamteer) {
        (function(wcf) {
            var _one_of_decls = /*#__PURE__*/ _class_private_field_loose_key._("_one_of_decls");
            let RoomData = class RoomData extends _googleprotobuf.Message {
                get members() {
                    return _googleprotobuf.Message.getRepeatedWrapperField(this, RoomData.RoomMember, 1);
                }
                set members(value) {
                    _googleprotobuf.Message.setRepeatedWrapperField(this, 1, value);
                }
                get field_2() {
                    return _googleprotobuf.Message.getFieldWithDefault(this, 2, 0);
                }
                set field_2(value) {
                    _googleprotobuf.Message.setField(this, 2, value);
                }
                get field_3() {
                    return _googleprotobuf.Message.getFieldWithDefault(this, 3, 0);
                }
                set field_3(value) {
                    _googleprotobuf.Message.setField(this, 3, value);
                }
                get field_4() {
                    return _googleprotobuf.Message.getFieldWithDefault(this, 4, 0);
                }
                set field_4(value) {
                    _googleprotobuf.Message.setField(this, 4, value);
                }
                get room_capacity() {
                    return _googleprotobuf.Message.getFieldWithDefault(this, 5, 0);
                }
                set room_capacity(value) {
                    _googleprotobuf.Message.setField(this, 5, value);
                }
                get field_6() {
                    return _googleprotobuf.Message.getFieldWithDefault(this, 6, 0);
                }
                set field_6(value) {
                    _googleprotobuf.Message.setField(this, 6, value);
                }
                get field_7() {
                    return _googleprotobuf.Message.getFieldWithDefault(this, 7, "0");
                }
                set field_7(value) {
                    _googleprotobuf.Message.setField(this, 7, value);
                }
                get field_8() {
                    return _googleprotobuf.Message.getFieldWithDefault(this, 8, "0");
                }
                set field_8(value) {
                    _googleprotobuf.Message.setField(this, 8, value);
                }
                static fromObject(data) {
                    const message = new RoomData({});
                    if (data.members != null) {
                        message.members = data.members.map((item)=>RoomData.RoomMember.fromObject(item));
                    }
                    if (data.field_2 != null) {
                        message.field_2 = data.field_2;
                    }
                    if (data.field_3 != null) {
                        message.field_3 = data.field_3;
                    }
                    if (data.field_4 != null) {
                        message.field_4 = data.field_4;
                    }
                    if (data.room_capacity != null) {
                        message.room_capacity = data.room_capacity;
                    }
                    if (data.field_6 != null) {
                        message.field_6 = data.field_6;
                    }
                    if (data.field_7 != null) {
                        message.field_7 = data.field_7;
                    }
                    if (data.field_8 != null) {
                        message.field_8 = data.field_8;
                    }
                    return message;
                }
                toObject() {
                    const data = {};
                    if (this.members != null) {
                        data.members = this.members.map((item)=>item.toObject());
                    }
                    if (this.field_2 != null) {
                        data.field_2 = this.field_2;
                    }
                    if (this.field_3 != null) {
                        data.field_3 = this.field_3;
                    }
                    if (this.field_4 != null) {
                        data.field_4 = this.field_4;
                    }
                    if (this.room_capacity != null) {
                        data.room_capacity = this.room_capacity;
                    }
                    if (this.field_6 != null) {
                        data.field_6 = this.field_6;
                    }
                    if (this.field_7 != null) {
                        data.field_7 = this.field_7;
                    }
                    if (this.field_8 != null) {
                        data.field_8 = this.field_8;
                    }
                    return data;
                }
                serialize(w) {
                    const writer = w || new _googleprotobuf.BinaryWriter();
                    if (this.members.length) writer.writeRepeatedMessage(1, this.members, (item)=>item.serialize(writer));
                    if (this.field_2 != 0) writer.writeInt32(2, this.field_2);
                    if (this.field_3 != 0) writer.writeInt32(3, this.field_3);
                    if (this.field_4 != 0) writer.writeInt32(4, this.field_4);
                    if (this.room_capacity != 0) writer.writeInt32(5, this.room_capacity);
                    if (this.field_6 != 0) writer.writeInt32(6, this.field_6);
                    if (this.field_7 != "0") writer.writeInt64String(7, this.field_7);
                    if (this.field_8 != "0") writer.writeInt64String(8, this.field_8);
                    if (!w) return writer.getResultBuffer();
                }
                static deserialize(bytes) {
                    const reader = bytes instanceof _googleprotobuf.BinaryReader ? bytes : new _googleprotobuf.BinaryReader(bytes), message = new RoomData();
                    while(reader.nextField()){
                        if (reader.isEndGroup()) break;
                        switch(reader.getFieldNumber()){
                            case 1:
                                reader.readMessage(message.members, ()=>_googleprotobuf.Message.addToRepeatedWrapperField(message, 1, RoomData.RoomMember.deserialize(reader), RoomData.RoomMember));
                                break;
                            case 2:
                                message.field_2 = reader.readInt32();
                                break;
                            case 3:
                                message.field_3 = reader.readInt32();
                                break;
                            case 4:
                                message.field_4 = reader.readInt32();
                                break;
                            case 5:
                                message.room_capacity = reader.readInt32();
                                break;
                            case 6:
                                message.field_6 = reader.readInt32();
                                break;
                            case 7:
                                message.field_7 = reader.readInt64String();
                                break;
                            case 8:
                                message.field_8 = reader.readInt64String();
                                break;
                            default:
                                reader.skipField();
                        }
                    }
                    return message;
                }
                serializeBinary() {
                    return this.serialize();
                }
                static deserializeBinary(bytes) {
                    return RoomData.deserialize(bytes);
                }
                constructor(data){
                    super();
                    Object.defineProperty(this, _one_of_decls, {
                        writable: true,
                        value: void 0
                    });
                    _class_private_field_loose_base._(this, _one_of_decls)[_one_of_decls] = [];
                    _googleprotobuf.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [
                        1
                    ], _class_private_field_loose_base._(this, _one_of_decls)[_one_of_decls]);
                    if (!Array.isArray(data) && typeof data == "object") {
                        if ("members" in data && data.members != undefined) {
                            this.members = data.members;
                        }
                        if ("field_2" in data && data.field_2 != undefined) {
                            this.field_2 = data.field_2;
                        }
                        if ("field_3" in data && data.field_3 != undefined) {
                            this.field_3 = data.field_3;
                        }
                        if ("field_4" in data && data.field_4 != undefined) {
                            this.field_4 = data.field_4;
                        }
                        if ("room_capacity" in data && data.room_capacity != undefined) {
                            this.room_capacity = data.room_capacity;
                        }
                        if ("field_6" in data && data.field_6 != undefined) {
                            this.field_6 = data.field_6;
                        }
                        if ("field_7" in data && data.field_7 != undefined) {
                            this.field_7 = data.field_7;
                        }
                        if ("field_8" in data && data.field_8 != undefined) {
                            this.field_8 = data.field_8;
                        }
                    }
                }
            };
            wcf.RoomData = RoomData;
            (function(RoomData) {
                var _one_of_decls = /*#__PURE__*/ _class_private_field_loose_key._("_one_of_decls");
                let RoomMember = class RoomMember extends _googleprotobuf.Message {
                    get wxid() {
                        return _googleprotobuf.Message.getFieldWithDefault(this, 1, "");
                    }
                    set wxid(value) {
                        _googleprotobuf.Message.setField(this, 1, value);
                    }
                    get name() {
                        return _googleprotobuf.Message.getFieldWithDefault(this, 2, "");
                    }
                    set name(value) {
                        _googleprotobuf.Message.setField(this, 2, value);
                    }
                    get state() {
                        return _googleprotobuf.Message.getFieldWithDefault(this, 3, 0);
                    }
                    set state(value) {
                        _googleprotobuf.Message.setField(this, 3, value);
                    }
                    static fromObject(data) {
                        const message = new RoomMember({});
                        if (data.wxid != null) {
                            message.wxid = data.wxid;
                        }
                        if (data.name != null) {
                            message.name = data.name;
                        }
                        if (data.state != null) {
                            message.state = data.state;
                        }
                        return message;
                    }
                    toObject() {
                        const data = {};
                        if (this.wxid != null) {
                            data.wxid = this.wxid;
                        }
                        if (this.name != null) {
                            data.name = this.name;
                        }
                        if (this.state != null) {
                            data.state = this.state;
                        }
                        return data;
                    }
                    serialize(w) {
                        const writer = w || new _googleprotobuf.BinaryWriter();
                        if (this.wxid.length) writer.writeString(1, this.wxid);
                        if (this.name.length) writer.writeString(2, this.name);
                        if (this.state != 0) writer.writeInt32(3, this.state);
                        if (!w) return writer.getResultBuffer();
                    }
                    static deserialize(bytes) {
                        const reader = bytes instanceof _googleprotobuf.BinaryReader ? bytes : new _googleprotobuf.BinaryReader(bytes), message = new RoomMember();
                        while(reader.nextField()){
                            if (reader.isEndGroup()) break;
                            switch(reader.getFieldNumber()){
                                case 1:
                                    message.wxid = reader.readString();
                                    break;
                                case 2:
                                    message.name = reader.readString();
                                    break;
                                case 3:
                                    message.state = reader.readInt32();
                                    break;
                                default:
                                    reader.skipField();
                            }
                        }
                        return message;
                    }
                    serializeBinary() {
                        return this.serialize();
                    }
                    static deserializeBinary(bytes) {
                        return RoomMember.deserialize(bytes);
                    }
                    constructor(data){
                        super();
                        Object.defineProperty(this, _one_of_decls, {
                            writable: true,
                            value: void 0
                        });
                        _class_private_field_loose_base._(this, _one_of_decls)[_one_of_decls] = [];
                        _googleprotobuf.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], _class_private_field_loose_base._(this, _one_of_decls)[_one_of_decls]);
                        if (!Array.isArray(data) && typeof data == "object") {
                            if ("wxid" in data && data.wxid != undefined) {
                                this.wxid = data.wxid;
                            }
                            if ("name" in data && data.name != undefined) {
                                this.name = data.name;
                            }
                            if ("state" in data && data.state != undefined) {
                                this.state = data.state;
                            }
                        }
                    }
                };
                RoomData.RoomMember = RoomMember;
            })(RoomData = wcf.RoomData || (wcf.RoomData = {}));
        })(iamteer.wcf || (iamteer.wcf = {}));
    })(com.iamteer || (com.iamteer = {}));
})(com || (com = {}));

//# sourceMappingURL=roomdata.js.map