/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.19.1
 * source: roomdata.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export declare namespace com.iamteer.wcf {
    class RoomData extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            members?: RoomData.RoomMember[];
            field_2?: number;
            field_3?: number;
            field_4?: number;
            room_capacity?: number;
            field_6?: number;
            field_7?: number;
            field_8?: number;
        });
        get members(): RoomData.RoomMember[];
        set members(value: RoomData.RoomMember[]);
        get field_2(): number;
        set field_2(value: number);
        get field_3(): number;
        set field_3(value: number);
        get field_4(): number;
        set field_4(value: number);
        get room_capacity(): number;
        set room_capacity(value: number);
        get field_6(): number;
        set field_6(value: number);
        get field_7(): number;
        set field_7(value: number);
        get field_8(): number;
        set field_8(value: number);
        static fromObject(data: {
            members?: ReturnType<typeof RoomData.RoomMember.prototype.toObject>[];
            field_2?: number;
            field_3?: number;
            field_4?: number;
            room_capacity?: number;
            field_6?: number;
            field_7?: number;
            field_8?: number;
        }): RoomData;
        toObject(): {
            members?: {
                wxid?: string | undefined;
                name?: string | undefined;
                state?: number | undefined;
            }[] | undefined;
            field_2?: number | undefined;
            field_3?: number | undefined;
            field_4?: number | undefined;
            room_capacity?: number | undefined;
            field_6?: number | undefined;
            field_7?: number | undefined;
            field_8?: number | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): RoomData;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): RoomData;
    }
    namespace RoomData {
        class RoomMember extends pb_1.Message {
            #private;
            constructor(data?: any[] | {
                wxid?: string;
                name?: string;
                state?: number;
            });
            get wxid(): string;
            set wxid(value: string);
            get name(): string;
            set name(value: string);
            get state(): number;
            set state(value: number);
            static fromObject(data: {
                wxid?: string;
                name?: string;
                state?: number;
            }): RoomMember;
            toObject(): {
                wxid?: string | undefined;
                name?: string | undefined;
                state?: number | undefined;
            };
            serialize(): Uint8Array;
            serialize(w: pb_1.BinaryWriter): void;
            static deserialize(bytes: Uint8Array | pb_1.BinaryReader): RoomMember;
            serializeBinary(): Uint8Array;
            static deserializeBinary(bytes: Uint8Array): RoomMember;
        }
    }
}
//# sourceMappingURL=roomdata.d.ts.map