/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.19.1
 * source: wcf.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */ "use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
const _interop_require_wildcard = require("@swc/helpers/_/_interop_require_wildcard");
const _googleprotobuf = /*#__PURE__*/ _interop_require_wildcard._(require("google-protobuf"));
 //# sourceMappingURL=wcf.d.ts.map

//# sourceMappingURL=wcf.d.js.map